apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: falco

helmCharts:
- name: falco
  releaseName: falco
  includeCRDs: true
  version: 2.0.18
  namespace: falco
  repo: https://falcosecurity.github.io/charts
  valuesFile: values.yaml